'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createServer}=require('../server.cjs');
const {serverPolicy}=require('../server-policy.cjs');
const origin='https://pocketman.example';
async function setup(t,options={}){const s=createServer({call:async()=>({body:{}}),close(){}},{publicOrigin:origin,...options});await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>s.close(r)));return (url,headers={},body='{}',method='POST')=>new Promise((resolve,reject)=>{const q=http.request({host:'127.0.0.1',port:s.address().port,path:url,method,headers:{Host:'pocketman.example',Origin:origin,'X-Cassette-Client':'1',...headers}},r=>{let text='';r.on('data',c=>text+=c);r.on('end',()=>resolve({status:r.statusCode,headers:r.headers,text}))});q.on('error',reject);q.end(body)})}
test('public deployment accepts only configured HTTPS origin and hides private/server files',async t=>{const request=await setup(t);assert.equal((await request('/',{},'', 'GET')).status,200);for(const h of [{Host:'evil.test'},{Origin:'http://pocketman.example'},{Origin:'https://evil.test'},{'Sec-Fetch-Site':'cross-site'}])assert.equal((await request('/api/netease/status',h)).status,403);for(const file of ['/server.cjs','/server-policy.cjs','/musickit/config.json','/.env','/package.json','/assets/../../musickit/key.p8','/assets/%2e%2e%2fkey.p8'])assert.equal((await request(file,{},'','GET')).status,404);assert.equal((await request('/healthz',{},'','GET')).status,200)});
test('public sessions are Secure, HttpOnly and host-only; invalid bodies are rejected',async t=>{const request=await setup(t);const response=await request('/api/netease/status');assert.equal(response.status,200);const cookie=response.headers['set-cookie'][0];assert.match(cookie,/^__Host-cassette_session=/);for(const flag of ['Secure','HttpOnly','SameSite=Strict','Path=/'])assert.ok(cookie.includes(flag));assert.ok(!cookie.includes('Domain='));for(const body of ['null','[]','1','"text"','{'])assert.equal((await request('/api/netease/search',{},body)).status,400);assert.equal((await request('/api/netease/search',{},JSON.stringify({keywords:'x'.repeat(17000)}))).status,413)});
test('production token binds the public origin without leaking signing material',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'walkman-public-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const {privateKey,publicKey}=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'});fs.writeFileSync(path.join(dir,'key.p8'),privateKey.export({type:'pkcs8',format:'pem'}));const file=path.join(dir,'config.json');fs.writeFileSync(file,JSON.stringify({key_id:'ABCDEFGHIJ',team_id:'0123456789',private_key_path:'key.p8'}));const request=await setup(t,{musicKitConfig:file});const response=await request('/api/apple-music/token');assert.equal(response.status,200);const token=JSON.parse(response.text).developerToken,[h,p,s]=token.split('.');assert.deepEqual(JSON.parse(Buffer.from(p,'base64url')).origin,[origin]);assert.ok(crypto.verify('sha256',Buffer.from(h+'.'+p),{key:publicKey,dsaEncoding:'ieee-p1363'},Buffer.from(s,'base64url')));assert.ok(!response.text.includes('PRIVATE KEY'))});
test('rate limit rejects excess requests and completed requests release capacity',async t=>{const request=await setup(t,{rateLimit:2,maxActive:1});assert.equal((await request('/api/netease/status')).status,200);assert.equal((await request('/api/netease/status')).status,200);const r=await request('/api/netease/status');assert.equal(r.status,429);assert.equal(r.headers['retry-after'],'60');assert.equal((await request('/healthz',{},'','GET')).status,200)});
test('production configuration fails closed on insecure or ambiguous origin',()=>{for(const publicOrigin of ['http://pocketman.example','https://pocketman.example/','https://pocketman.example/path','https://u:p@pocketman.example','https://127.0.0.1','garbage'])assert.throws(()=>serverPolicy({publicOrigin}));assert.equal(serverPolicy({publicOrigin:origin}).origin({headers:{host:'pocketman.example'},socket:{remoteAddress:'8.8.8.8'}}),null)});
test('demo audio supports bounded and suffix ranges for seeking',async t=>{const request=await setup(t);const r=await request('/assets/neon-night.mp3',{Range:'bytes=0-99'},'','GET');assert.equal(r.status,206);assert.equal(r.headers['content-length'],'100');assert.match(r.headers['content-range'],/^bytes 0-99\//);assert.equal(r.headers['content-type'],'audio/mpeg');const suffix=await request('/assets/neon-night.mp3',{Range:'bytes=-30'},'','GET');assert.equal(suffix.status,206);assert.equal(suffix.headers['content-length'],'30');for(const range of ['bytes=9999999999-','bytes=30-10','bytes=-0','bytes=0-1,5-9'])assert.equal((await request('/assets/neon-night.mp3',{Range:range},'','GET')).status,416)});
